Fix code base on review comments
SSLcom/acme4j pull request #2
Opened 2024-01-16 16:21 UTC by ifindthanh

- Rollback ClientTest.java as default one
- Using sslcom-dv-ecc for SslComAcmeProvider instead of sslcom-dv-rsa
- Adding separated client test class for Ssl with EAB supported

2024-01-16 16:46 UTC, fergadis requested changes

2024-01-16 16:46 UTC, fergadis commented on acme4j-example/src/main/java/org/shredzone/acme4j/example/SSLClientWithEabTest.java
> +        //Session session = new Session("acme://letsencrypt.org/staging");
```suggestion
        // Create a session for SSL.com.
        // Use "acme://ssl.com" for production server
        Session session = new Session("acme://ssl.com/staging");
```

2024-01-16 16:46 UTC, fergadis commented on ssl-truststore
Please remove this file.

2024-01-17 00:02 UTC, ifindthanh commented on ssl-truststore
it is already in my commit
<img width="919" alt="image" src="https://github.com/SSLcom/acme4j/assets/11816930/b2679ab6-9fd3-46e7-ac0d-ecd85a751c30">

2024-01-17 16:56 UTC, codelux approved these changes
changes accepted

2024-01-17 16:56 UTC, merged